### ISSUE TITLE
RFE: Add error percentage to logs

### ISSUE THREAD

**Issue by apexswqa** [redsaz/lognition#13]
Please add error percentage to the table of log stats at the top of the log view, so the user can see all error percentages for a run at a glance. Otherwise one has to scroll down to each endpoint's error percentage graph.

**Comment by redsaz** [comment]
This was added by commit e8d6c8b70966fdcb541d5eb9aee73573cd947032 (though incorrectly referenced issue #6, not this issue, #13.)
