### ISSUE TITLE
RFE: Allow custom content to be uploaded to a report

### ISSUE THREAD

**Issue by redsaz** [redsaz/lognition#25]
A report is supposed to be a comparison view of various logs. Sometimes the graphs and tables provided by a report are not sufficient. It would be nice if external scripts can upload their own content to a report.

**Comment by say-paul** [comment]
Ability to upload SVG(graph) would be a good start. Also I think this can be part of the standard comparison report  in a separate tab maybe.

**Comment by redsaz** [comment]
I agree, those seem like useful addtions,

**Comment by redsaz** [comment]
The code is now committed to master and will be in the next release of lognition. Folks can now upload attachments to any review by doing the following:

    curl -v -F "description=Example image to demonstrate attachments" \
        -F "name=Example" \
        -F "file=@Pictures/example.png;type=image/png" \
        -F "path=example.png" \
        http://localhost:8080/reviews/1/attachments

Once the attachment is uploaded, the user can see a new attachment tab when visiting the review at http://localhost:8080/reviews/1 (or whatever review id). If the attachment was an image, it will get its own tab, named with the same name as given in the `name` parameter in the example.

The attachment can be viewed (if an image) or downloaded by either clicking the link in the attachments tab, or by navigating to the attachment with the format `/reviews/{reviewId}/attachments/{path}`. For example, for reviewId 1 and attachment path "example.png", you can go to http://localhost:8080/reviews/1/attachments/example.png to view the image.

This can be taken advantage of with the review description as well. Since review (and log) descriptions are markdown/commonmark, the same example image can be displayed in the example review's description itself by adding `
![Example of an image in review description](./attachments/example.png "Example Image")` when editing the review.

Currently, uploading, deleting, and moving of attachments can only be done via the HTTP API. There are plans to add these features to the UI itself as well but is not part of this issue.
