### ISSUE TITLE
RFE: Add endpoint to get list of logs matching label selector

### ISSUE THREAD

**Issue by redsaz** [redsaz/lognition#26]
All logs can have labels (sometimes known as tags) which is used to choose which logs to include in a report. If there was an endpoint to return a list of logs matching a label selector, then that would help with external scripts that might want to use lognition.

**Comment by say-paul** [comment]
This can Priority 1

**Comment by redsaz** [comment]
Code is now committed for this.

**Comment by redsaz** [comment]
Documentation still needs added for this, but for now, the way it's done is this:

curl -v -H 'Accept: application/json' "$BASE_URL/logs/?labelSelector=exampleLabel"
