### ISSUE TITLE
RFE: Add reporting on http status codes

### ISSUE THREAD

**Issue by apexswqa** [redsaz/lognition#6]
It would be really nice for each log to display a count of http status codes, and maybe a corresponding percentage for each.
Not sure how useful this would be as part of a review; maybe a graph comparing status code counts across logs would be nice, but definitely less important.

**Comment by redsaz** [comment]
Excellent! I think this would be valuable as well.

**Comment by redsaz** [comment]
This feature of displaying the counts of each status code has been implemented for some time now, but without reporting percentages. If the percentages is needed as well, another RFE can be opened.
